[build]
builder = "nixpacks"

[deploy]
startCommand = "sh release.sh && gunicorn material_accounting.wsgi --bind 0.0.0.0:$PORT --workers 2 --timeout 120"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
