# Generated by Django 6.0.1 on 2026-02-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_alter_issue_created_by_alter_receipt_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='destination',
            field=models.CharField(default='Не указано', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receipt',
            name='source',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
