# Generated by Django 6.0.1 on 2026-02-14 09:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_contractor_finishedproduct_section_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contractor',
            old_name='contact_person',
            new_name='contact_info',
        ),
        migrations.RemoveField(
            model_name='contractor',
            name='phone',
        ),
        migrations.AddField(
            model_name='contractor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contractor',
            name='address',
            field=models.CharField(max_length=255),
        ),
    ]
