# Generated by Django 6.0.1 on 2026-02-14 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0007_rename_contact_person_contractor_contact_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.section'),
        ),
    ]
