# Generated by Django 6.0.1 on 2026-02-16 17:38

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0009_material_contractor_material_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('receipt', 'Приход'), ('issue', 'Расход'), ('scrap', 'Списание'), ('edit', 'Редактирование'), ('delete', 'Удаление'), ('create', 'Создание')], max_length=20)),
                ('quantity', models.FloatField(default=0)),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Запись аудита',
                'verbose_name_plural': 'Журнал аудита',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='FinishedProduct',
        ),
        migrations.RemoveField(
            model_name='turnoverstatement',
            name='material',
        ),
        migrations.AlterModelOptions(
            name='contractor',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ['-created_at'], 'verbose_name': 'Расход', 'verbose_name_plural': 'Расходы'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='receipt',
            options={'ordering': ['-created_at'], 'verbose_name': 'Приход', 'verbose_name_plural': 'Приходы'},
        ),
        migrations.AlterModelOptions(
            name='scrap',
            options={'ordering': ['-created_at'], 'verbose_name': 'Списание', 'verbose_name_plural': 'Списания'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='issue',
            name='destination',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='issue',
            name='purpose',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='material',
            name='color',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='material',
            name='composition',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='material',
            name='density',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='min_stock',
            field=models.FloatField(default=10),
        ),
        migrations.AddField(
            model_name='material',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='material',
            name='width',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='document_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='receipt',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 2, 16, 17, 36, 54, 62851, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='issue',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='warehouse.material'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='quantity',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='material',
            name='contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.contractor'),
        ),
        migrations.AlterField(
            model_name='material',
            name='quantity',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='material',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='warehouse.section'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='material',
            name='unit',
            field=models.CharField(default='м', max_length=50),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.contractor'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='warehouse.material'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='quantity',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='scrap',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scraps', to='warehouse.material'),
        ),
        migrations.AlterField(
            model_name='scrap',
            name='quantity',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='warehouse.material'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Shipment',
        ),
        migrations.DeleteModel(
            name='TurnoverStatement',
        ),
    ]
