# Generated by Django 6.0.1 on 2026-02-18 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0011_alter_auditlog_options_alter_issue_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Цена за метр, кг или штуку', max_digits=12, verbose_name='Цена за единицу'),
        ),
    ]
