# Generated by Django 6.0.1 on 2026-02-17 06:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '0011_alter_auditlog_options_alter_issue_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('climate_type', models.CharField(choices=[('cold', 'Холодный климат (зима)'), ('moderate', 'Умеренный климат (демисезон)'), ('hot', 'Жаркий климат (лето)'), ('extreme', 'Экстремальные условия')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('temperature_range', models.CharField(help_text='Например: от -40°C до -20°C', max_length=50)),
            ],
            options={
                'verbose_name': 'Категория спецодежды',
                'verbose_name_plural': 'Категории спецодежды',
                'ordering': ['climate_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(help_text='Номер партии производства', max_length=50, unique=True)),
                ('size', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=50)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('quantity_produced', models.PositiveIntegerField(default=1)),
                ('production_date', models.DateField()),
                ('status', models.CharField(choices=[('in_production', 'В производстве'), ('quality_check', 'Проверка качества'), ('ready', 'Готов к отгрузке'), ('shipped', 'Отгружен')], default='in_production', max_length=20)),
                ('warehouse_location', models.CharField(blank=True, help_text='Место хранения на складе готовой продукции', max_length=50)),
                ('material_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('labor_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('produced_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produced_products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Готовая продукция',
                'verbose_name_plural': 'Готовая продукция',
                'ordering': ['-production_date', 'batch_number'],
            },
        ),
        migrations.CreateModel(
            name='MaterialConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_required', models.FloatField(help_text='Требовалось по норме')),
                ('quantity_used', models.FloatField(help_text='Фактически использовано')),
                ('quantity_waste', models.FloatField(default=0, help_text='Отходы/брак')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.material')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_consumptions', to='production.product')),
            ],
            options={
                'verbose_name': 'Расход материала',
                'verbose_name_plural': 'Расход материалов',
            },
        ),
        migrations.CreateModel(
            name='ProductShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('shipment_date', models.DateField()),
                ('document_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='production.product')),
                ('shipped_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('shipped_to', models.ForeignKey(limit_choices_to={'contractor_type': 'customer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.contractor')),
            ],
            options={
                'ordering': ['-shipment_date'],
            },
        ),
        migrations.CreateModel(
            name='ProductTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: Костюм нефтяника зимний', max_length=255)),
                ('article', models.CharField(max_length=100, unique=True)),
                ('protection_level', models.CharField(choices=[('basic', 'Базовая защита'), ('standard', 'Стандартная защита'), ('high', 'Повышенная защита'), ('max', 'Максимальная защита')], default='standard', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('weight_kg', models.FloatField(help_text='Вес комплекта в кг', validators=[django.core.validators.MinValueValidator(0)])),
                ('sizes_available', models.CharField(default='44-46, 48-50, 52-54, 56-58, 60-62', max_length=255)),
                ('colors_available', models.CharField(default='Темно-синий, Оранжевый, Красный', max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/templates/')),
                ('technical_drawing', models.ImageField(blank=True, null=True, upload_to='products/drawings/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='production.productcategory')),
            ],
            options={
                'verbose_name': 'Шаблон изделия',
                'verbose_name_plural': 'Шаблоны изделий',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='production.producttemplate'),
        ),
        migrations.CreateModel(
            name='ProductMaterialRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_per_unit', models.FloatField(help_text='Количество материала на одно изделие', validators=[django.core.validators.MinValueValidator(0.01)])),
                ('waste_percent', models.FloatField(default=5, help_text='Норма отходов в %')),
                ('notes', models.TextField(blank=True, help_text='Особенности раскроя, расположение деталей')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in_products', to='warehouse.material')),
                ('product_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_requirements', to='production.producttemplate')),
            ],
            options={
                'verbose_name': 'Норма расхода материала',
                'verbose_name_plural': 'Нормы расхода материалов',
                'unique_together': {('product_template', 'material')},
            },
        ),
    ]
