# Generated by Django 6.0.1 on 2026-02-18 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='markup_percent',
            field=models.DecimalField(decimal_places=2, default=20.0, help_text='Процент наценки на готовую продукцию', max_digits=5, verbose_name='Наценка %'),
        ),
        migrations.AddField(
            model_name='product',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Цена с учетом наценки', max_digits=12, verbose_name='Цена продажи за штуку'),
        ),
        migrations.AlterField(
            model_name='product',
            name='labor_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='material_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
