# Generated by Django 6.0.1 on 2026-02-02 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('storekeeper', 'Кладовщик'), ('master', 'Мастер'), ('director', 'Директор')], max_length=20),
        ),
    ]
